using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Mindspace.Services;

public class ExportService : IExportService
{
    private readonly IJournalService _journalService;

    public ExportService(IJournalService journalService)
    {
        _journalService = journalService;
    }

    public async Task ExportEntriesToPdfAsync(int userId, DateTime from, DateTime to)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        
        QuestPDF.Settings.EnableDebugging = false;
        QuestPDF.Settings.UseEnvironmentFonts = true;

        var entries = await _journalService.GetAllEntriesAsync(userId);

        var filtered = entries
            .Where(e => e.Date.Date >= from.Date && e.Date.Date <= to.Date)
            .OrderBy(e => e.Date)
            .ToList();

        if (!filtered.Any())
            throw new InvalidOperationException("No journal entries found for the selected date range.");

        var filePath = Path.Combine(
            FileSystem.Current.AppDataDirectory,
            $"Mindspace_Journal_{DateTime.Now:yyyyMMdd_HHmm}.pdf"
        );

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text("Mindspace Journal Export")
                    .FontSize(22)
                    .Bold()
                    .AlignCenter();

                page.Content().Column(col =>
                {
                    foreach (var entry in filtered)
                    {
                        col.Item().PaddingVertical(10).BorderBottom(1).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2);

                        col.Item().Text(entry.Title)
                            .FontSize(16)
                            .Bold();

                        col.Item().Text(entry.Date.ToString("MMMM dd, yyyy"))
                            .FontSize(10)
                            .FontColor(QuestPDF.Helpers.Colors.Grey.Darken1);

                        col.Item().PaddingTop(5).Text(entry.Content)
                            .FontSize(12);
                    }
                });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Mindspace • ");
                        x.CurrentPageNumber();
                        x.Span(" / ");
                        x.TotalPages();
                    });
            });
        })
        .GeneratePdf(filePath);

        await Launcher.Default.OpenAsync(new OpenFileRequest
        {
            File = new ReadOnlyFile(filePath)
        });
    }
}
